# Site settings
title: Mahendrata Harpi ⚡
description: >-
  He's write in Bahasa about what interests him and as a journal 
  for documentation things that he learned, meet him  <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise
mode: "dark" # default theme "dark" | "light"

# Profile settings
author:
  name: Mahendrata Harpi
  bio: >-
    He's write in Bahasa about what interests him and as a journal 
    for documentation things that he learned, meet him  <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
  username: piharpi
  email: contact@harpi.rocks
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://harpi.rocks"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

disqus:
  shortname: 'harpi'

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - bangsring.gemspec
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
