# Site settings
title: Mahendrata Harpi | piharpi
# projects: true # false to hide my work
description:  >-
 This Blog is place where i'm writing about web technology 
 what i like and as journal for documentation things what i learn, meet me <a href="https://github.com/piharpi" target="_blank">@github</a>.
lang: en-US
timezone: Asia/Jakarta
icon: 'favicon.ico'  

# User settings
author: 
  name: Mahendrata Harpi
  username: piharpi
  email: justharpi@gmail.com
  avatar: '/assets/img/coco.png'

# Url settings
url: https://piharpi.com
baseurl: ""
permalink: /:categories/:title/
google_analytics: UA-105586262-1
fb_appid: 1806380839422028

collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
syntax_highlighter: rouge

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      image: /assets/img/avatar.png
      comments: false

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules 
  - bangsring.gemspec
  - CODE_OF_CONDUCT.md
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
