# Site settings
title: Choirul M. Harpi | piharpi
description: >-
  This Blog is place where i'm writing about web technology 
  what i like and as journal for documentation things what i learn, meet me <a href="https://github.com/piharpi" target="_blank">@github</a>.
lang: en-US
timezone: Asia/Jakarta
icon: "favicon.ico"
# theme: "dark"

# User settings
author:
  name: Mahendrata Harpi
  username: piharpi
  email: justharpi@gmail.com
  avatar: "/assets/img/coco.png"

# Url settings
url: https://piharpi.com
baseurl: ""
permalink: /blog/:categories/:title/
google_analytics: UA-105586262-1
fb_appid: ""

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - bangsring.gemspec
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
